### ISSUE TITLE
Font metric information not found for system fonts

### ISSUE THREAD

**Issue by davben** [plfjohnson/devEMF#2]
I am trying to produce EMF-versions of plots using a system font.

```
library(ggplot2)
library(devEMF)

emf("./test.emf", width = 16, height = 10, units = "cm", emfPlus = TRUE, emfPlusFont = TRUE)
ggplot(mtcars, aes(wt, mpg)) +
  geom_point() +
  labs(x = "Weight (tons)", y = "Fuel efficiency (mpg)") +
  theme_light(base_family = "Arial Narrow")
dev.off()
```

While the desired EMF-file is created and actually uses Arial Narrow for any text, I still receive the following warning:

```
In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  devEMF: font metric information not found for family 'Arial Narrow'; using 'Helvetica' instead
```

Arial Narrow is available and shows up when checking via `fc-list`.

I'm running R via R-Studio Server on Ubuntu 20.04.5. libfreetype-dev and libxft-dev are both installed. Does devEMF require a (virtual) Display to work?

```
> session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.1 (2022-06-23)
 os       Ubuntu 20.04.5 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  de_DE.UTF-8
 ctype    de_DE.UTF-8
 tz       Europe/Berlin
 date     2023-04-25
 rstudio  2022.07.1+554 Spotted Wakerobin (server)
 pandoc   2.18 @ /usr/lib/rstudio-server/bin/quarto/bin/tools/ (via rmarkdown)
```

**Comment by plfjohnson** [comment]
> Does devEMF require a (virtual) Display to work?

Currently, yes.  devEMF accesses system-installed fonts through Xft, which in turn requires opening a connection to an X server.

However, I believe the code could be re-worked to directly use fontconfig, which would avoid the dependence on X.  I'll investigate and post updates here.

**Comment by plfjohnson** [comment]
The change from Xft to fontconfig was easier than I feared.  Please try installing from github and test in your context.

**Comment by davben** [comment]
Thank you so much for dealing with this!

As it is now, I'm getting a compilation error:
```
In file included from fontmetrics.h:42,
                 from devEMF.cpp:48:
/usr/include/freetype2/freetype/freetype.h:24:2: error: #error "`ft2build.h' hasn't been included yet!"
   24 | #error "`ft2build.h' hasn't been included yet!"
      |  ^~~~~
/usr/include/freetype2/freetype/freetype.h:25:2: error: #error "Please always use macros to include FreeType header files."
   25 | #error "Please always use macros to include FreeType header files."
      |  ^~~~~
/usr/include/freetype2/freetype/freetype.h:26:2: error: #error "Example:"
   26 | #error "Example:"
      |  ^~~~~
/usr/include/freetype2/freetype/freetype.h:27:2: error: #error "  #include <ft2build.h>"
   27 | #error "  #include <ft2build.h>"
      |  ^~~~~
/usr/include/freetype2/freetype/freetype.h:28:2: error: #error "  #include FT_FREETYPE_H"
   28 | #error "  #include FT_FREETYPE_H"
      |  ^~~~~
```
Re-adding `#include <ft2build.h>` in fontmetrics.h resolves this and the package is being compiled. But I don't know if this makes sense and whether it's in line with the rest of your code changes.

**Comment by plfjohnson** [comment]
Ha.  Good reminder not to mess with something that isn't broken (the change in ```#include``` worked fine on my computer, but clearly not on all).  I have pushed a reversion of the ```#include``` statements.  This change does not impact the rest of the modifications.

**Comment by davben** [comment]
Thank you again, works like a charm now!
